// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXEndjAyGTF05QKAR-WJNcQ2Ci4CPZe-8',
    appId: '1:483656026091:web:b76273b24e3460ebf03bae',
    messagingSenderId: '483656026091',
    projectId: 'whatsapp-clone-7cc3b',
    authDomain: 'whatsapp-clone-7cc3b.firebaseapp.com',
    storageBucket: 'whatsapp-clone-7cc3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1dhhflvCW78D0HxnbyY0eVPXRpdyM8fo',
    appId: '1:483656026091:android:e277c0460f09f3d5f03bae',
    messagingSenderId: '483656026091',
    projectId: 'whatsapp-clone-7cc3b',
    storageBucket: 'whatsapp-clone-7cc3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC91JTc7FcTD3VhFshv2rnN2ccef6n6x_8',
    appId: '1:483656026091:ios:da612afa4f6fa26ef03bae',
    messagingSenderId: '483656026091',
    projectId: 'whatsapp-clone-7cc3b',
    storageBucket: 'whatsapp-clone-7cc3b.appspot.com',
    iosClientId: '483656026091-nhih611pl5jkprigqdgi0f3ju4pr3tfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC91JTc7FcTD3VhFshv2rnN2ccef6n6x_8',
    appId: '1:483656026091:ios:da612afa4f6fa26ef03bae',
    messagingSenderId: '483656026091',
    projectId: 'whatsapp-clone-7cc3b',
    storageBucket: 'whatsapp-clone-7cc3b.appspot.com',
    iosClientId: '483656026091-nhih611pl5jkprigqdgi0f3ju4pr3tfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
